#!/bin/bash

# This assumes you have setup the macos dev tools first
# Install homebrew!
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# Install tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

~/brew-install
~/npm-install
