#!/bin/bash

# This assumes you have setup the macos dev tools first
# Install homebrew!
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

~/brew-install
~/npm-install
